### Recuperar todos los Productos
GET http://localhost:2345/products

### Recuperar un producto por su id
GET http://localhost:2345/products/3

### Filtrar por categoria
GET http://localhost:2345/products?category=men's clothing

### Crear un nuevo producto
POST http://localhost:2345/products
Content-Type: application/json

  {
    "title": "Chaqueta",
    "price": 100,
    "description": "Chaqueta de cuero",
    "category": "men's clothing",
    "image": "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_t.png",
    "rating": {
      "rate": 4.7,
      "count": 500
    }
  }

### Eliminar un producto por su ID
DELETE http://localhost:2345/products/18
